### ISSUE TITLE
Clone4 sample does not compile

### ISSUE THREAD

**Issue by johnholliday** [postsharp/Caravela.Samples#55]
The implementation of AddEmptyCloneMembersAspect fails to compile because it does not implement BuildEligibility method.

**Comment by svick** [comment]
[`BuildEligibility` is a default interface method on .Net 6](https://github.com/postsharp/Metalama.Framework/blob/d6f6577/Metalama.Framework/Eligibility/IEligible.cs), so the sample as is does compile.

If you copy the code into a project that targets an older framework (like .Net Framework or .Net Standard 2.0), you will indeed need to implement `BuildEligibility` (as an empty method), to make the code compile, because those frameworks don't support default interface methods.

**Comment by svick** [comment]
Closing as answered.
